version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbit-container'
    hostname: rabbit
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbit_connection

  sender:
    image: sender-image
    build:
        context: .
        dockerfile: Dockerfile1.dockerfile
    container_name: 'sender-container'
    stdin_open: true
    tty: true
    depends_on: 
        - rabbitmq
    volumes:
        - ~/.docker-conf/sender/data/:/var/lib/sender/
        - ~/.docker-conf/sender/log/:/var/log/sender
    networks:
        - rabbit_connection

  reciever:
    image: receiver-image
    build:
        context: .
        dockerfile: Dockerfile2.dockerfile
    container_name: 'receiver-container'
    stdin_open: true
    tty: true
    depends_on: 
        - rabbitmq
    volumes:
        - ~/.docker-conf/receiver/data/:/var/lib/receiver/
        - ~/.docker-conf/receiver/log/:/var/log/receiver
    networks:
        - rabbit_connection

networks:
  rabbit_connection:
    driver: bridge